language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- yarn
- yarn global add https://github.com/ebidel/lighthouse-ci
script:
- yarn build
after_success:
  - if [ $TRAVIS_PULL_REQUEST ]; then yarn lh --pwa=100 --perf=100 https://ecatch-kyst.firebaseapp.com; else echo "No need to run Lighthouse"; fi