language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- yarn
- yarn global add https://github.com/ebidel/lighthouse-ci
script:
- yarn build
after_success:
  - yarn lh https://ecatch-kyst.firebaseapp.com --pwa=100